job_name = run_test
universe = vanilla
executable = run_generic_job.py
arguments = postgresql://postgres:mysecretpassword@localhost:5435/workflows_tutorial_workflows_tutorial_db a0a8ffc9-1a23-496e-9a7f-02ee21b981e4 d335b0a6-13ab-432d-a6ef-74c6ea50691f http://admin:@localhost:8181/geoserver/rest/ http://admin:@localhost:8181/geoserver/rest/ tethysapp.workflows_tutorial.workflows.basic_workflow.BasicWorkflow workflow_params.json test 0 run_test_out.json
initialdir = $(job_name)
logdir = logs
log = $(logdir)/$(job_name).$(cluster).log
output = $(logdir)/$(job_name).$(cluster).$(process).out
error = $(logdir)/$(job_name).$(cluster).$(process).err
transfer_executable = TRUE
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
transfer_input_files = ../run_generic_job.py, ../workflow_params.json
transfer_output_files = run_test_out.json
environment = FDB_ROOT_DIR=/fdbs;GEOSERVER_CLUSTER_PORTS=None;GDAL_DATA=/home/jakeymac/miniconda3/envs/workflows-ext-dev/share/gdal;GDAL_DRIVER_PATH=/home/jakeymac/miniconda3/envs/workflows-ext-dev/lib/python3.12/site-packages/osgeo/gdalplugins;PROJ_DATA=/home/jakeymac/miniconda3/envs/workflows-ext-dev/share/proj;PROJ_DEBUG=3
request_cpus = 1

queue 1
